version: "3"
services:
  app:
    image: unoxi/tippspiel
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.services.${TRAEFIK_NAME}.loadbalancer.server.port=80
      - traefik.http.routers.${TRAEFIK_NAME}.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.${TRAEFIK_NAME}.entrypoints=https
      - traefik.http.routers.${TRAEFIK_NAME}.tls=true
      - traefik.http.routers.${TRAEFIK_NAME}.tls.certresolver=le
    networks:
      - internal
      - proxy
    environment:
      SITE_NAME: ${SITE_NAME}
      LOGO_URL: ${LOGO_URL}
      FAVICON_URL: ${FAVICON_URL}
      DOMAIN: ${DOMAIN}
      # MAIL INFO FOR PW RESET MAILS
      SENDER_MAIL: ${SENDER_MAIL}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_PROTOCOL: ${SMTP_PROTOCOL}

  mariadb:
    image: "mariadb:10.9.1-rc"
    restart: always
    volumes:
      - "mariadb:/var/lib/mysql"
    environment:
      MARIADB_ROOT_PASSWORD: "hardtoguess"
      MARIADB_DATABASE: "tippspiel"
      MARIADB_USER: "profi"
      MARIADB_PASSWORD: "iforp"
    networks:
      - internal

volumes:
  mariadb:

networks:
  internal:
  proxy:
    external: true
